stack-set: guardduty-main
main-account: true
#all-regions: true
excluded-regions:
  - eu-north-1
organization-variables: true
max-concurrent-percentage: 100
region: us-east-1
tags:
  ValidateMainAccount: true
  ValidateAllRegions: true
