stack-set: config-rules
all-accounts: true
#all-regions: true
excluded-regions:
  - eu-north-1
main-account-parameter: true
max-concurrent-percentage: 100
organization-variables: true
region: us-east-1
vars:
  EnabledRegions:
    - us-east-1
  GuardDutyUnavailableRegions:
    - ap-northeast-3
  EnabledConfigRules:
    EIP_ATTACHED: AWS::EC2::EIP
    INCOMING_SSH_DISABLED: AWS::EC2::SecurityGroup
    RDS_INSTANCE_PUBLIC_ACCESS_CHECK: AWS::RDS::DBInstance
    CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED: AWS::CloudTrail::Trail
    VPC_FLOW_LOGS_ENABLED: AWS::EC2::VPC
    S3_BUCKET_PUBLIC_READ_PROHIBITED:
      ["AWS::S3::Bucket", "AWS::S3::AccountPublicAccessBlock"]
    S3_BUCKET_PUBLIC_WRITE_PROHIBITED:
      ["AWS::S3::Bucket", "AWS::S3::AccountPublicAccessBlock"]
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: us-east-1
