stack-set: stack-set-execution-role
execution-role-name: AdministratorAccessRole
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
max-concurrent-percentage: 100
#all-subaccounts: false
accounts:
  - 206924800932
  - 815637454826
regions:
  - ap-northeast-2
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: ap-northeast-2
